Clean up checkpointing, add checkpointing to GCS. (#30)
Tested w/ following cases:

* LOCAL
  * start from scratch, local checkpoints and tags.json get created
  * resume from the last run, resumes correctly, adds checkpoints, and
  tags get adjusted correctly

* GCS
  * start from scratch, chpts and tags.json get created in GCS
  * resume from the last run, resumes correctly, adds checkpoints, tags
    adjusted correctly

We currently cannot directly save to gcs, due to:

```python
  File
"/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch/serialization.py",
line 372, in save
    _legacy_save(obj, opened_file, pickle_module, pickle_protocol)
  File
"/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch/serialization.py",
line 451, in _legacy_save
    serialized_storages[key]._write_file(f, _should_read_directly(f),
True)
  File
"/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch/serialization.py",
line 292, in _should_read_directly
    return f.fileno() >= 0
  File
"/anaconda3/envs/torch-xla-nightly/lib/python3.6/site-packages/torch_xla/utils/gcsfs.py",
line 59, in fileno
    raise OSError('Not supported on GCS files: {}'.format(self._path))
OSError: Not supported on GCS files:
gs://taylanpytorch/checkpoint-test/checkpoint1.pt
```

To get around this, we save locally and then send that file to gcs